spring:
  application:
    name: isep-config-server

  cloud:
    config:
      server:
        git:
          uri: ${https://github.com/MiaDev4/dbe-cloud-server.git}
          refresh-rate: 0
          default-label: main
          clone-on-start: true

  profiles:
    active: ${SERVEUR_PROFILE:dev}
server:
  port: ${CFG_SERVER_PORT:8888}

